### ISSUE TITLE
Change class location to Generator

### ISSUE THREAD

**Issue by manuerwin** [manuerwin/code-club-salesforce-volunteers#15]
3-4 email templates reference the old office location.

**Comment by stephenpstanley** [comment]
Templates that need to be updated:

- [x] **[Change Class Location]** Assistant - upcoming class details https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UIPi%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516314788956

- [x] **[Change Class Location]** Leader - upcoming class details https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UIMP%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516314925720

- [x] **[Change Class Location]** Student - class reminder https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UIMo%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516315261405

- [x] **[Change Class Location]** Student - class reminder ACTIVITY LOG https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UKE4%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516315322424

- [x]  **[remove reference to Scratch account and add whatever's needed for HTML/CSS]**  Student (attended) - post class let them have details of the work ACTIVITY LOG https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UKDu%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516315023022

- [x]  **[remove reference to Scratch account and add whatever's needed for HTML/CSS]**  Student (attended) - post class let them have details of the work that they did https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UK6U%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516315128807

- [x]  **[remove reference to Scratch account and add whatever's needed for HTML/CSS]**  Student (canceled) - post class let them have details of the work ACTIVITY LOG https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UKDz%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516315174880

- [x]  **[remove reference to Scratch account and add whatever's needed for HTML/CSS]**  Student (canceled) - post class let them have details of the work they missed https://codeclub-nz.lightning.force.com/one/one.app#/setup/page?nodeId=CommunicationTemplatesEmail&address=%2F00X7F000000UK7I%3Fsetupid%3DCommunicationTemplatesEmail%26isdtp%3Dp1&a:t=1516315236959

**Comment by stephenpstanley** [comment]
All templates listed above have been updated 

- References to PWC Tower replaced with the Generator Board Room
- Reference to the need for a Scratch account replaced with the need for a Trinket account to allow them to save their work - and the need for parental permission needed if the student is aged under 13 years old
