### ISSUE TITLE
Summer'18 has changed CSS classes to use BEM notation - and may break custom css

### ISSUE THREAD

**Issue by stephenpstanley** [manuerwin/code-club-salesforce-volunteers#19]
see GUS W-4983326 which says this is WAD
Release notes: https://releasenotes.docs.salesforce.com/en-us/summer18/release-notes/rn_lc_css.htm

@manuerwin is there any easy way to find any css classes that contain "--"?

**Comment by manuerwin** [comment]
Text search across a local file copy of the source should do it.

**Comment by stephenpstanley** [comment]
So just doing a git pull (assuming that it's the same as the live org - which it probably isn't) will get it onto my hard drive?


What's the easiest way to make sure that what's on git is the same as what's in the org first?


________________________________

**Comment by manuerwin** [comment]
Yes that will pull down the latest from git, however you'll need to use
your favourite IDE to retrieve the metadata from the org into that local
git repo.

**Comment by stephenpstanley** [comment]
Found two instances of "--" replaced them with "_"

I was using vs.code for the first time and not only did it search and find them, it suggested the fix.

Seems like a useful tool.
