### ISSUE TITLE
Class Attendance List fields (for Attendance and Contact) should be clickable

### ISSUE THREAD

**Issue by manuerwin** [manuerwin/code-club-salesforce-volunteers#7]
Make Name and Attendee fields in the list clickable so it takes you to the record detail for the clicked item.  The ATT-0000156 - style field to the Attendee record and the Person's name to the relevant contact record. Manu I'm getting close here but I can't substitute the ID's on the end of the url.  See Lines 48 and 53 of listAttendance.cmp

**Comment by stephenpstanley** [comment]
Resolved: added href tags which get concatenated with the record ID and now produce a valid url so you can click on them them and navigate directly to the Attendee record if you click on the Attendance Name or the Contact record if you click on the Contact name.
