### ISSUE TITLE
Post class emails go to the old parental email address

### ISSUE THREAD

**Issue by stephenpstanley** [manuerwin/code-club-salesforce-volunteers#9]
When a parent's email address changes, these updates don't get propagated to the parental email address currently denormalised onto the child's contact record

On attending or cancelling from a class, when the appropriate attendance record button is clicked, the student gets a suitable email.  If we don't have the student's email address, then the email should be sent to the parent responsible

Currently, the parental email address is denormalised onto the Contact record for the student.  It is an email field (not a formula field as email alerts cannot be fired from a formula field)

Work required is

- [x] add a checkbox Parental_Email_Updated__c to the Account record. Visibility Admins, Do not add to page layout, default unchecked

- [x] add a checkbox Parental_Email_Updated__c to the contact record. Visibility Admins, Do not add to page layout, default unchecked

- [x] BP which fires on create and update of the parent contact's email address - if they are the parental contact, then set a checkbox on the related account record to flag that it has been updated Field: Parental_Email_Updated__c.  

- [x] Add a new BP which fires when Account.Parental_Email_Updated__c is set to true.  This should update the Contact.Parental_Email_Updated__c checkbox to TRUE for any related contact records associated for that account 

- [x] Add a new BP which fires when Contact.Parental_Email_Updated__c is set to true.  This should propagate the changed parental email address to any contact attendance records associated with contacts from that account and set the Account.Parental_Email_Updated__c checkbox to false and the ContactParental_Email_Updated__c checkbox to false

- [x] update the BP which populates the Notification_email_copy__c field with the Parental email address on creation of the student's Attendance record to be derived from:
 if student email is empty, then use the parental email on the account record, otherwise use the email address on the student's contact record

**Comment by stephenpstanley** [comment]
Note that the original issue described in the Quip[ backlog contained these three items.  When this issue has been fixed, all three scenarios need to be fixed.

Use case: If there are existing Attendance records and the student's or the responsible parent's email address changes, then the emails that are sent before and after the class must be sent to the revised email address.

Scenarios to test: 
1. Child's (Contact type=Student) email address is updated (and was not previously blank) or the parent's email address is updated) all future email associated with future-dated attendance records should be sent to the revised email address    

2. Child's (Contact type=Student) pre-update email address is blank and the contact is in role=student on any future attendance records, then future emails associated with these future-dated attendance records should be sent to the contact's new email address

3.  This was included in Scenario 1

Currently, the email address to send to is denormalised into the  Attendance.notification_copy_email__c field in order to simplify the email template.  This field should be removed and the email templates should look up the field mentioned in the issue description on the Account instead

**Comment by stephenpstanley** [comment]
All tasks listed in the original issue have been implemented

**Comment by manuerwin** [comment]
Interested to talk the solution through with you.
Did you consider using the “update child records from parent” PB functionality?
https://help.salesforce.com/articleView?id=000213419&type=1
